
# General settings
dist: trusty
sudo: false
language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
notifications:
  email: false
branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/

# Build stages
stages:
  - name: test
  # - name: release
  #   if: branch = master

# Build jobs
jobs:
  include:
    - stage: test
      install:
        - npm install
      script:
        - npm run test:client -- --coverage --forceExit
        - npm run test:server -- --coverage --forceExit
      after_success:
        # Upload coverage if the tests are running green
        - npm install -g codeclimate-test-reporter
        - codeclimate-test-reporter < coverage/lcov.info

    - stage: release
      if: branch = master
      install:
        - npm install
      script:
        - npm run build
      # before_deploy:
      #   # Login to Git to be able to make commits (required by automatic-release)
      #   - git config --global user.name "Alex Anderson";
      #   - git config --global user.email "alexanderson1993@gmail.com";
      #   - git config credential.helper "store --file=.git/credentials";
      #   - echo "https://$GH_TOKEN:@github.com" > .git/credentials;
      deploy:
        provider: releases
        api_key:
          secure: "$GH_TOKEN"
        file:
          - "zips/thorium-linux.zip"
          - "zips/thorium-macos.zip"
          - "zips/thorium-win.exe.zip"
        skip_cleanup: true
        on:
          tags: true

  
