language: node_js
node_js:
  - "node"
dist: trusty
sudo: false
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
before_install: sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
install:
  - npm install
  - npm run build-css
script:
  - npm run test:client -- --coverage --forceExit
  - npm run test:server -- --coverage --forceExit
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
